### ISSUE TITLE
Replace Zurb Foundation's 

### ISSUE THREAD

**Issue by aslakhellesoy** [kamens/jQuery-menu-aim#2]
In https://groups.google.com/group/foundation-framework-/browse_thread/thread/27ecd8c6312d3973 I ask the Foundation team if they want to adopt the Amazon technique.

In the meanwhile - would you be interested in providing an example that uses this library as a replacement for Foundation's [top bar navigation sub menus](http://foundation.zurb.com/docs/components/top-bar.html)?

**Comment by Shelob9** [comment]
That's a user group forum, to talk to the developers use the github repro at https://github.com/zurb/foundation

I use Foundation 3, havn't decided how I feel about 4 yet. I am going to try and find time to take a stab at adapting this to foundation, if anyone else is intrested in working on this, let me know.

**Comment by kamens** [comment]
I won't have time to make this specific example, but I'd love to see it in action if you get the chance!
