### ISSUE TITLE
Re-entering a menu after exit

### ISSUE THREAD

**Issue by djrees** [kamens/jQuery-menu-aim#20]
Firstly, thanks for the great work !

I'm currently having an issue; where once the 'exitMenu' option is called, the previous active item can no-longer be opened - until another row item is opened.

Is there a way to fix this ? Or am I using exitMenu incorrectly?

Thanks

**Comment by zfedoran** [comment]
Your `exitMenu` function needs to `return true;`

https://github.com/kamens/jQuery-menu-aim/blob/master/jquery.menu-aim.js#L123

**Comment by djrees** [comment]
Thank you.
