### ISSUE TITLE
Can we achieve same thing for horizontal menu

### ISSUE THREAD

**Issue by color2life** [kamens/jQuery-menu-aim#3]
How to make it work with horizontal menu
for example.
http://www.adidas.co.uk/shop

**Comment by kostin1221** [comment]
https://github.com/kamens/jQuery-menu-aim/pull/7

**Comment by kamens** [comment]
Check out the "submenuDirection" option provided by https://github.com/kamens/jQuery-menu-aim/commit/5e321a8a6905ba93697d91d84458b331986b0ee6

Choosing a value of "above" or "below" lets menu-aim support horizontal menus. Lemme know how it goes.

**Comment by sam3k** [comment]
Is there a sample of how the menu is used multiple times in a horizontal menu?
