### ISSUE TITLE
Destroy function?

### ISSUE THREAD

**Issue by evanhuntley** [kamens/jQuery-menu-aim#38]
I'm using the plugin on a responsive site, which uses a differently styled menu for the small screen view.  I already have javascript in place to manage calling different functions depending on the viewport.

How can I turn off menu-aim so that I can manage the two different menus?  The issue I have is when I render the page at a large viewport size and then resize to a small screen view - the menu-aim behaviors continue to occur, and I basically just want to turn them off.

**Comment by bobbyrenwick** [comment]
Hey @evanhuntley check out #41

**Comment by rbrlortie** [comment]
Any update on this years later? Is this still maintained? There are 23 pull requests.
