### ISSUE TITLE
Menu on the right

### ISSUE THREAD

**Issue by carlosjeurissen** [kamens/jQuery-menu-aim#4]
Hi Developer,

I'm facing a problem with this jquery plugin. It is made for menus which are on the left, but my menu in black menu is on the right.
What things should I change to solve this problem?

Thanks in advance,

Carlos

**Comment by ShintaroNippon** [comment]
HI Guys, i'm facing the same problem, can someone help to apply this in RTL version...

Thanks in advance.
Carlos Vieira

**Comment by ShintaroNippon** [comment]
hi, after a research on this, i believe i found a solution...
In method called slope (slope of a line) in line 230
i have put this code (changes)

```
        var upperSlope = slope(loc, lowerRight ),
        lowerSlope = slope(loc, upperRight),
        prevUpperSlope = slope(prevLoc, lowerRight),
        prevLowerSlope = slope(prevLoc, upperRight );
```

The solution was change the variables upperRight and lowerRight in slope method call calculation.
I hope this could help. For me it works.

Thanks
Carlos Vieira

**Comment by kamens** [comment]
Thanks all. This issue is on my radar, and although I don't have time to immediately solve it, I hope to make the code friendlier for all directions of menus in the future.

**Comment by kamens** [comment]
Check out the "submenuDirection" option provided by https://github.com/kamens/jQuery-menu-aim/commit/5e321a8a6905ba93697d91d84458b331986b0ee6

Choosing a value of "right" lets menu-aim support menus that open to the right. Lemme know how it goes.
