### ISSUE TITLE
Can get sub menu below to work....

### ISSUE THREAD

**Issue by jamierussell-50** [kamens/jQuery-menu-aim#68]
Hi, I'm trying to get the drop down to work that appears below the main menu; however when I move the mouse from the main menu to the sub menu it disappears. I've put it on a test page here...

http://uk.monsoon.co.uk/view/content/ip-test

I've tried changing the top position and integrating some of the other pull requests on here but nothing has worked as if yet so any thoughts or suggestions would be appreciated! Code is below and can also be viewed on the source code of the page...Many thanks in advance

<script>

        var $menu = $(".dropdown-menu");

        // jQuery-menu-aim: <meaningful part of the example>
        // Hook up events to be fired on menu row activation.
        $menu.menuAim({
            activate: activateSubmenu,
            deactivate: deactivateSubmenu,
            submenuDirection: "below"
        });
        // jQuery-menu-aim: </meaningful part of the example>

        // jQuery-menu-aim: the following JS is used to show and hide the submenu
        // contents. Again, this can be done in any number of ways. jQuery-menu-aim
        // doesn't care how you do this, it just fires the activate and deactivate
        // events at the right times so you know when to show and hide your submenus.
        function activateSubmenu(row) {
            var $row = $(row),
                submenuId = $row.data("submenuId"),
                $submenu = $("#" + submenuId),
                height = $menu.outerHeight(),
                width = $menu.outerWidth();
            // Show the submenu
            $("div[rel='"+submenuId+"']").css('display','block');
            $submenu.css({
                display: "block",
                top: 25,
                left: 0,  // main should overlay submenu
                height: height - 4  // padding for main dropdown's arrow
            });

            // Keep the currently activated row's highlighted look
            $row.find("a").addClass("maintainHover");
        }

        function deactivateSubmenu(row) {
            var $row = $(row),
                submenuId = $row.data("submenuId"),
                $submenu = $("#" + submenuId);
            // Hide the submenu and remove the row's highlighted look
            $("div[rel='"+submenuId+"']").css('display','none');
            $submenu.css("display", "none");
            $row.find("a").removeClass("maintainHover");
        }

        // Bootstrap's dropdown menus immediately close on document click.
        // Don't let this event close the menu if a submenu is being clicked.
        // This event propagation control doesn't belong in the menu-aim plugin
        // itself because the plugin is agnostic to bootstrap.
        $(".dropdown-menu li").click(function(e) {
            e.stopPropagation();
        });

        $(document).click(function() {
            // Simply hide the submenu on any click. Again, this is just a hacked
            // together menu/submenu structure to show the use of jQuery-menu-aim.
            $(".mega-arrow").css("display", "none");
            $(".popover").css("display", "none");
            $("a.maintainHover").removeClass("maintainHover");
        });

    </script>

**Comment by banesto** [comment]
Hi! When clicking the link I'm redirected to homepage.

**Comment by jamierussell-50** [comment]
Hi banesto, what country are you viewing the site in? It might be directing you to a site other than the UK. If you click this link:
http://uk.monsoon.co.uk/?countrycheck=true&languageCode=en_gb

and then go to http://uk.monsoon.co.uk/view/content/ip-test

that should hopefully solve it. Thanks,

**Comment by banesto** [comment]
Now I can see it. Maybe you could stip the code more gruesome - especially javascript? Because there are too many libraries involved - many of them could interfere.

**Comment by banesto** [comment]
But my first guess would be that there's is some other javascript that handles hover actions.

**Comment by jamierussell-50** [comment]
Ok thanks for the feedback, I can't strip out any of the other javascript libraries unfortunately as they are not under our access rights. It doesn't throw back any JS errors and it is technically working just not in the way I want it to at the moment so I assume there is something we can do with menu-aim to get it working right.

Thanks,

**Comment by banesto** [comment]
In the original site there is a dropdown menu as well - you should find out how it get's handled - it should be the one to trigger mouseleave action.

**Comment by banesto** [comment]
As to "no JS errors" - if there's no errors then whether something is overriden or is not called at all. My best advise is to put a real sample page with bare stuff in it - basic html, menu css and jquery with menu aim plugin javascript.

**Comment by jamierussell-50** [comment]
Hi Banesto, what do you mean by in the original site? If you mean our current live one then yes we do have one but we have to change the structure of it due to the new menu being 100% width amongst other things. I tried putting alerts in on some of the options such as exit and exitMenu and they were firing but it doesn't allow you to navigate down to the submenu if you do that. I've created the page as basic as I can get it on my side (without the site header and footer)....there are some JS includes but I've tested it in a static page when it doesn't have those and it's still getting exactly the same behaviour:

http://uk.monsoon.co.uk/view/content/nav-test

Many thanks,

**Comment by jamierussell-50** [comment]
Are there any examples you know of that have a drop down menu working on mouse over that use menu-aim I could use as a reference? The only ones I have found so far are left to right and onclick behaviour. Thanks,

**Comment by banesto** [comment]
Oh, I see it now. The markup is not correct, you have to put submenu block (`<div id="submenu-women"></div>` for instance) inside corresponding `li` element.

**Comment by jamierussell-50** [comment]
Hmm ok that's going to be a pain as I'm struggling to get the submenu to be 100% width with the top nav remaining centered with several items, part of the reason I was looking at using this over our current one (See example below so you can see what I mean):
http://uk.monsoon.co.uk/view/content/ip-test

I'll have a play around with it but if you have any other suggestions they'd be most welcome. Kind regards,
Jamie

**Comment by jamierussell-50** [comment]
I managed to solve the issue I was having....I had a relative position on the top level 'li' items...so when the sub menu was shown it was restricting the width to the same as the top nav item. Once I removed the relative position it went to 100% of the width. Kind regards,
