### ISSUE TITLE
Nested Menu with Menu-aim

### ISSUE THREAD

**Issue by m4w** [kamens/jQuery-menu-aim#69]
I know there is a topic allready, but it is very old and no one replied. 
Has anyone of you successfully implemented a multi level navigation with menu aim? The example has only one level, and I have at least there to deal with, its for category browsing with many child and grandchild categories. 
But Nesting menuAim into itself does not seem to work out of the box.

**Comment by m4w** [comment]
I got close to an solution, but I have no time to investigate it further, but it is possible if you implement the functions "activate", "deactivate" and "exitMenu".
But if somebody has a working solution, I would be most thankfull.

**Comment by banesto** [comment]
I believe this is what you're looking for: http://codepen.io/mattweb/pen/pkvlh. This is coming from this [issue](https://github.com/kamens/jQuery-menu-aim/issues/43)

**Comment by m4w** [comment]
Perfect. Thanks.

**Comment by banesto** [comment]
No problem. You can close issue now :smile:
