### ISSUE TITLE
Does a non-jquery version exist?

### ISSUE THREAD

**Issue by nilssolanki** [kamens/jQuery-menu-aim#75]
Thank you for your work on making this pattern possible. I'm currently working on a project where we can't use jQuery. Do you know if anybody has turned this into a plain JS/DOM script yet?

**Comment by nilssolanki** [comment]
Found it: https://github.com/yuanqing/menu-aim

**Comment by kintaro1981** [comment]
well is not the same... the linked one works with only with delay 😢
