### ISSUE TITLE
submenu cannot be triggered again after clicking close it in the example

### ISSUE THREAD

**Issue by dentrite** [kamens/jQuery-menu-aim#9]
If a menuitem is hovered,  the submenu div will show up as expected, and clicking the area outside the menu, the submenu div will close, however when I  hovered the same menuitem again, the submenu div didn't appear anymore unless I move to another menuitem and then move back. 

```
    $(document).click(function() {
        // Simply hide the submenu on any click. Again, this is just a hacked
        // together menu/submenu structure to show the use of jQuery-menu-aim.
        $(".popover").css("display", "none");
    });
```

Maybe it has to do with the code above. I guess the code doesn't deactivate the menu properly.

**Comment by tmo256** [comment]
+1

**Comment by kamens** [comment]
Check out https://github.com/kamens/jQuery-menu-aim/commit/dd4adf5b5dfca9dc13b90b8998f8ce2a210a1a52 and let me know what you think. If you supply a function for the exitMenu option and let it return true, then your submenu will be deactivated when the mouse leaves the menu entirely.

People want different use cases when the mouse exits the menu entirely, so I hope that the provided exitMenu callback gives them the choice/power that they need.
